// airlines.js
// 航空公司 ICAO 代碼對照表 (一個更全面的列表)

const airlineCodeMap = {
    'CPA': 'Cathay Pacific',
    'HKE': 'HK Express',
    'CRK': 'Hong Kong Airlines',
    'GBA': 'Greater Bay Airlines',
    'UAL': 'United Airlines',
    'AAL': 'American Airlines',
    'DAL': 'Delta Air Lines',
    'ANA': 'All Nippon Airways',
    'JAL': 'Japan Airlines',
    'CAL': 'China Airlines',
    'EVA': 'EVA Air',
    'SIA': 'Singapore Airlines',
    'THA': 'Thai Airways',
    'MAS': 'Malaysia Airlines',
    'BAW': 'British Airways',
    'AFR': 'Air France',
    'KLM': 'KLM Royal Dutch Airlines',
    'DLH': 'Lufthansa',
    'QFA': 'Qantas',
    'ANZ': 'Air New Zealand',
    'UAE': 'Emirates',
    'QTR': 'Qatar Airways',
    'ETD': 'Etihad Airways',
    'KAL': 'Korean Air',
    'AAR': 'Asiana Airlines',
    'PAL': 'Philippine Airlines',
    'ACA': 'Air Canada',
    'CES': 'China Eastern Airlines',
    'CSN': 'China Southern Airlines',
    'FIN': 'Finnair',
    'SBI': 'S7 Airlines',
    'SWR': 'Swiss International Air Lines',
    'THY': 'Turkish Airlines',
    'VNL': 'Vanilla Air',
    'JST': 'Jetstar Japan',
    'APJ': 'Peach Aviation',
    'AXM': 'AirAsia X',
    'ALK': 'SriLankan Airlines',
    'HVN': 'Vietnam Airlines',
    'JSA': 'Jetstar Asia Airways',
    'GIA': 'Garuda Indonesia',
    'MPH': 'Martinair',
    'FDX': 'FedEx Express',
    'UPS': 'UPS Airlines',
    'MGL': 'Mongolian Airlines',
    'TSC': 'Air Transat',
    'VIR': 'Virgin Atlantic',
    'WJA': 'WestJet',
    'XAX': 'AirAsia',
    'SCX': 'SunExpress',
    'SAS': 'Scandinavian Airlines',
    'RYR': 'Ryanair',
    'EZY': 'EasyJet',
    'EIN': 'Aer Lingus',
    'IBE': 'Iberia',
    'TAP': 'TAP Air Portugal',
    'AUA': 'Austrian Airlines',
    'AIC': 'Air India',
    'JAI': 'Jet Airways',
    'SVA': 'Saudia',
    'ELY': 'El Al',
    'ETH': 'Ethiopian Airlines',
    'MSR': 'EgyptAir',
    'RAM': 'Royal Air Maroc',
    'SAA': 'South African Airways',
    'LAN': 'LATAM Chile',
    'AMX': 'Aeroméxico',
    'AVA': 'Avianca',
    // ... 這個列表已經比之前詳盡很多，可以覆蓋大部分情況 ...
};